add_test( clear /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir/general_tree_tests [==[--test-case=clear]==])
set_tests_properties( clear PROPERTIES WORKING_DIRECTORY /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir LABELS)
add_test( [==[default constructor]==] /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir/general_tree_tests [==[--test-case=default constructor]==])
set_tests_properties( [==[default constructor]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir LABELS)
add_test( [==[copy constructor]==] /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir/general_tree_tests [==[--test-case=copy constructor]==])
set_tests_properties( [==[copy constructor]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir LABELS)
add_test( [==[root value construction]==] /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir/general_tree_tests [==[--test-case=root value construction]==])
set_tests_properties( [==[root value construction]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir LABELS)
add_test( [==[root value construction (move)]==] /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir/general_tree_tests [==[--test-case=root value construction (move)]==])
set_tests_properties( [==[root value construction (move)]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir LABELS)
add_test( [==[move constructor]==] /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir/general_tree_tests [==[--test-case=move constructor]==])
set_tests_properties( [==[move constructor]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir LABELS)
add_test( create_root /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir/general_tree_tests [==[--test-case=create_root]==])
set_tests_properties( create_root PROPERTIES WORKING_DIRECTORY /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir LABELS)
add_test( [==[create_root (move)]==] /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir/general_tree_tests [==[--test-case=create_root (move)]==])
set_tests_properties( [==[create_root (move)]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir LABELS)
add_test( emplace_root /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir/general_tree_tests [==[--test-case=emplace_root]==])
set_tests_properties( emplace_root PROPERTIES WORKING_DIRECTORY /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir LABELS)
add_test( [==[delete left child]==] /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir/general_tree_tests [==[--test-case=delete left child]==])
set_tests_properties( [==[delete left child]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir LABELS)
add_test( [==[delete right sibling]==] /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir/general_tree_tests [==[--test-case=delete right sibling]==])
set_tests_properties( [==[delete right sibling]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir LABELS)
add_test( insert_left_child /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir/general_tree_tests [==[--test-case=insert_left_child]==])
set_tests_properties( insert_left_child PROPERTIES WORKING_DIRECTORY /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir LABELS)
add_test( [==[insert_left_child (move)]==] /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir/general_tree_tests [==[--test-case=insert_left_child (move)]==])
set_tests_properties( [==[insert_left_child (move)]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir LABELS)
add_test( [==[insert_left_child (emplacement)]==] /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir/general_tree_tests [==[--test-case=insert_left_child (emplacement)]==])
set_tests_properties( [==[insert_left_child (emplacement)]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir LABELS)
add_test( [==[insert_left_child (tree)]==] /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir/general_tree_tests [==[--test-case=insert_left_child (tree)]==])
set_tests_properties( [==[insert_left_child (tree)]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir LABELS)
add_test( insert_right_sibling /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir/general_tree_tests [==[--test-case=insert_right_sibling]==])
set_tests_properties( insert_right_sibling PROPERTIES WORKING_DIRECTORY /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir LABELS)
add_test( [==[insert_right_sibling (move)]==] /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir/general_tree_tests [==[--test-case=insert_right_sibling (move)]==])
set_tests_properties( [==[insert_right_sibling (move)]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir LABELS)
add_test( [==[insert_right_sibling (emplacement)]==] /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir/general_tree_tests [==[--test-case=insert_right_sibling (emplacement)]==])
set_tests_properties( [==[insert_right_sibling (emplacement)]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir LABELS)
add_test( [==[insert_right_sibling (tree)]==] /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir/general_tree_tests [==[--test-case=insert_right_sibling (tree)]==])
set_tests_properties( [==[insert_right_sibling (tree)]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir LABELS)
add_test( general_tree::node /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir/general_tree_tests [==[--test-case=general_tree::node]==])
set_tests_properties( general_tree::node PROPERTIES WORKING_DIRECTORY /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir LABELS)
add_test( [==[node null safety]==] /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir/general_tree_tests [==[--test-case=node null safety]==])
set_tests_properties( [==[node null safety]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir LABELS)
add_test( [==[asssigment operator(move)]==] /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir/general_tree_tests [==[--test-case=asssigment operator(move)]==])
set_tests_properties( [==[asssigment operator(move)]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir LABELS)
add_test( [==[assigment operator]==] /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir/general_tree_tests [==[--test-case=assigment operator]==])
set_tests_properties( [==[assigment operator]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir LABELS)
add_test( [==[equality operator]==] /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir/general_tree_tests [==[--test-case=equality operator]==])
set_tests_properties( [==[equality operator]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir LABELS)
add_test( [==[deep copy parent pointers]==] /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir/general_tree_tests [==[--test-case=deep copy parent pointers]==])
set_tests_properties( [==[deep copy parent pointers]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/general-tree-cxx/general-tree-cxx/_codeql_build_dir LABELS)
set( general_tree_tests_TESTS clear [==[default constructor]==] [==[copy constructor]==] [==[root value construction]==] [==[root value construction (move)]==] [==[move constructor]==] create_root [==[create_root (move)]==] emplace_root [==[delete left child]==] [==[delete right sibling]==] insert_left_child [==[insert_left_child (move)]==] [==[insert_left_child (emplacement)]==] [==[insert_left_child (tree)]==] insert_right_sibling [==[insert_right_sibling (move)]==] [==[insert_right_sibling (emplacement)]==] [==[insert_right_sibling (tree)]==] general_tree::node [==[node null safety]==] [==[asssigment operator(move)]==] [==[assigment operator]==] [==[equality operator]==] [==[deep copy parent pointers]==])
